### ISSUE TITLE
When enabling a zone that doesn't exist in the config

### ISSUE THREAD

**Issue by testeddoughnut** [objectrocket/opsy#152]
Traceback (most recent call last):
  File "contrib/uwsgi/scheduler.py", line 7, in <module>
    scheduler = Scheduler(config)
  File "./hourglass/scheduler.py", line 14, in **init**
    with create_app(self.config_file).app_context():
  File "./hourglass/app.py", line 22, in create_app
    parse_config(app)
  File "./hourglass/app.py", line 53, in parse_config
    app.config['zones'][zone] = app.config[zone]
KeyError: 'HKQ1'

**Comment by cryptk** [comment]
I think that once this is resolved, we will be in a good place to call v0.1 complete.

**Comment by testeddoughnut** [comment]
I'm comfortable with bumping the version to v0.1 without this being resolved. I'm including the fix in my plugins update.

**Comment by testeddoughnut** [comment]
Closing, this was fixed in #177
