### ISSUE TITLE
Timeout's not properly caught by poller

### ISSUE THREAD

**Issue by cryptk** [objectrocket/opsy#160]
raises the following traceback:

```
Traceback (most recent call last):
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/hourglass_naglitejs/cache.py", line 100, in get
    response = yield from session.get(url)
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/aiohttp/client.py", line 529, in __iter__
    resp = yield from self._coro
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/aiohttp/client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/aiohttp/connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/aiohttp/connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 524, in create_connection
    yield from tasks.wait(fs, loop=self)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 331, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "/usr/lib/python3.4/asyncio/tasks.py", line 410, in _wait
    yield from waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 269, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contrib/uwsgi/scheduler.py", line 10, in <module>
    scheduler.run_tasks()
  File "./hourglass/scheduler.py", line 46, in run_tasks
    results = self.loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/hourglass_naglitejs/cache.py", line 111, in update_objects
    results = yield from self.get(session, url)
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/hourglass_naglitejs/cache.py", line 101, in get
    return (yield from response.json())
  File "/opt/hourglass/.virtualenvs/hourglass/lib/python3.4/site-packages/aiohttp/helpers.py", line 488, in __exit__
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

**Comment by cryptk** [comment]
FWIW, this was not experienced on the latest version, so I am unsure if this issue has been addressed already or not

**Comment by testeddoughnut** [comment]
This has been fixed. Closing this out.
